project:
  type: website

website:
  title: "KP_SMPA3230_Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - portfolio.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



