project:
  type: website
  output-dir: docs
  
website:
  title: "KP_SMPA3230_Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - portfolio.qmd
  page-footer: 
    left: "Copyright 2022, Kelli Pang" 
    right: 
      - icon: github
        href: https://github.com/kellipang
      


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



