project:
  type: website
  output-dir: docs
  
website:
  title: "Kelli's Data Journalism Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: https://docs.google.com/document/d/1dC94o7Tt_9sP-zoqCXTh0F4mpJBis5ZP/edit?usp=sharing&ouid=102064502494717724204&rtpof=true&sd=true
        text: Resume
      - about.qmd
      - portfolio.qmd
      - walkthrough.qmd
      - paper.qmd
      - academicpaper.qmd
  page-footer: 
    left: "Copyright 2022, Kelli Pang" 
    right: 
      - icon: github
        href: https://github.com/kellipang
      


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



