project:
  type: website
  output-dir: docs
  
website:
  title: "Kelli's Data Journalism Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: https://drive.google.com/file/d/14u28VhYGZ50hmFvCYQt7AN-kI1ybr1QO/view?usp=sharing
        text: Resume
      - about.qmd
      - portfolio.qmd
      - walkthrough.qmd
      - paper.qmd
      - academicpaper.qmd
      - va_elections.qmd
  page-footer: 
    left: "Copyright 2022, Kelli Pang" 
    right: 
      - icon: github
        href: https://github.com/kellipang
      


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



