---
title: "Academic Paper"
---

The following text is a paper I wrote for intermediate finance that outlines the role of over the counter derivatives in the 2008 financial crisis.  

### **The History and Future of OTC Derivatives**

From the trading of clay tokens in ancient Mesopotamia to Japan’s Dojima Rice Exchange in the 1730s, various forms of financial derivatives have appeared throughout human history. Like many other financial processes, modern-day derivative trading is primarily electronic. While today's trading methods look far different from historical practices, the primary purpose of financial derivatives remains the same. Derivatives are financial securities “whose value depends on (or derives from) the value of an underlying asset, reference rate or index” (Salifu). Through these financial contracts, two parties can bet on future changes in an underlying asset. A derivative’s underlying asset can be nearly anything– even another derivative. Traders use popular derivatives like forwards, futures contracts, and credit default swaps, to efficiently transfer risk between participating parties. There are two different ways to trade derivatives: through regulated exchanges or over-the-counter. 

In this paper, I will be focusing on the history of the unregulated, over-the-counter derivatives market, specifically Brooksley Born’s 1998 concept release, and how OTC derivatives contributed to the 2008 financial crisis. Following my analysis, I will propose solutions to issues regarding transparency and systemic risk in the OTC market. 

##### **What are Over-the-Counter Derivatives?**

Unlike traditional derivatives, OTC trading happens in a decentralized market and does not involve clearing organizations. While this allows OTC derivatives to be highly customizable and fit parties’ specific preferences, the lack of regulation exposes traders to counterparty risk.  Since OTC trades are not subject to clearinghouse rules, parties are granted more privacy at the cost of public transparency. Critics of OTC derivatives cite systemic risk and lack of transparency as the most concerning issues. 

In addressing the Senate Banking Committee in March 2002, former Federal Reserve Chairman Alan Greenspan called OTC derivatives, “a major contributor to the flexibility and resiliency of our financial system” (Salifu). When institutions and individuals redistribute their risk via OTC trading, they are “able to lower their cost of capital, manage their credit exposures, and increase their competitiveness both in the United States and the rest of the world” (Salifu). Because OTC derivatives are inherently reliant on other assets, their widespread use has allowed for a complex, interconnectivity to develop between different financial institutions and their respective markets. Under proper precautions, OTC derivatives are powerful financial instruments in managing business risk. 

##### **The U.S. Commodity Futures Trading Commission 1998 Concept Release**

The U.S. Commodity Futures Trading Commission, created by Congress in 1974, is an independent federal agency that regulates U.S. commodity futures contracts. Although OTC derivatives and futures contracts share many similar characteristics, Congress and the CFTC “worked to create legal certainty around the notion that OTC derivatives were not futures “ (Rose). This was done under pressure from the financial industry to promote growth in the OTC market. Financiers encouraged the market’s rapid development because they believed it was indicative of a strong economy. Congress and the CFTC officially defined OTC derivatives as tailor-made securities between two sophisticated parties not containing an exchange or requiring counterparty creditworthiness; however, they never clarified whether or not the derivatives were legally futures (Rose). Because this clarification was not made, there was confusion regarding whether or not OTC derivatives fell under the CFTC’s regulatory domain.

Brooksley Born was appointed as chairwoman and commissioner of the CFTC in August 1996 by President Bill Clinton. A former “lawyer with a track record for activist causes”, Born was known for being passionately progressive, especially in comparison to some of her “absolutist” colleagues (Schmitt). At the time, Greenspan was a firm believer that the markets would correct themselves. The lack of regulation in place reflected this belief and was largely supported by other financial leaders. 

From 1992 to 1997, the OTC market quintupled in value from $5.3 to $29 trillion (Rose). Concerned by the accelerated growth in the OTC market, Born directed the CFTC to compile information about the market in 1997 to determine “whether the terms and conditions of existing exemptions for OTC derivatives needed adjustment” (Rose). In 1998, Born shared the Concept Release, a general set of questions asking for public insight on the inner workings of the market and regulation of OTC derivatives. 

Despite intending for the Concept Release to simply gather public opinion and gain a better understanding of the OTC market, Born and her team received great backlash for even insinuating that the market may require oversight. Greenspan, along with Arthur Levitt, the Securities and Exchange Commission Chairman, and Robert Rubin, Treasury Secretary, promptly released a joint statement after the Concept Release’s publication and followed up with a letter to Congress a month later. In both, Greenspan, Levitt, and Rubin brought forth their concerns over an increase in the legal uncertainty of the derivative market and rejected the idea that OTCs fell under the CFTC’s jurisdiction. The trio proposed legislation to install oversight on the CFTC and prevent the agency from taking any further action over the OTC derivative market, resulting in H.R. 4062, or the Financial Derivatives Supervisory Improvement Act.

The Financials Derivatives Supervisory Improvement Act of 1998 advanced the idea that the Working Group on Financial Derivatives must study current regulations on derivative markets, recommend changes to modernize the regulations, and report their findings to Congress. Additionally, the act barred the CFTC from proposing policy or releasing statements without the Treasury Secretary’s approval. Because the Working Group on Financial Derivatives is composed of the Treasury of Secretary, and Chairmen of the Federal Reserve, SEC, and CFTC, Greenspan, Levitt, and Rubin designed the legislation to outnumber Born. The passing of H.R. 4062 would effectively strip the power to publicly question and discuss potential changes to the OTC market from Born and the CFTC.

Greenspan defended his belief in free markets, exclaiming that “The primary source of regulatory effectiveness has always been private traders being knowledgeable of their counterparties” (Greenspan). In Greenspan’s eyes, high credit ratings, the threat of legal fines, and care for reputation were enough to protect the market from major losses. Of course, Greenspan was unable to predict the rise in faulty credit rating and subsequent increase in subprime mortgages that would happen within the next decade. For Born to doubt the market’s ability to self-correct and suggest regulation, at the time, was absurd because Greenspan believed that “Government regulation can only act as a backup” (Greenspan).  

Before ending her own testimony, Born cautioned Congress that “Losses resulting from the misuse of OTC derivatives instruments or from sales practice abuses in the OTC derivatives market can affect many Americans” (Born). Because of the interconnected and complex nature of OTC derivatives, losses in the OTC derivative market inevitably have a widespread impact. Nevertheless, Congressional leaders disregarded Born and the CFTC, listened to Greenspan, and implemented H.R. 4062. In late 2000, Congress implemented the Commodity Futures Modernization Act which further ensured the OTC derivative market would not be regulated. By placing full trust in financial professionals and the market’s ability to self-correct, regulatory leaders led the world into the worst financial crisis since the Great Depression. 

##### **Over-the-Counter Derivatives and the Great Recession**

As Born predicted, the OTC derivatives market suffered major losses in 2008, and in turn, affected many Americans. OTC derivatives, specifically in the form of credit default swaps, played a prime role in intensifying the impact of the Great Recession. 

Designed in the 1990s to help banks reduce their risk, credit default swaps are a type of OTC derivative where a buyer pays the seller to protect them in case of a credit event. For example, if a firm faces bankruptcy, fails to pay, or reorganizes and can no longer fulfill its contract with an investor, an investor who bought a credit default swap would be compensated by the seller of the swap. Credit default swaps are similar to credit insurance, however, because they are classified as OTC derivatives they are not subject to state insurance regulations. Without insurance or OTC regulations, “CDS dealers had no regulatory obligation to hold capital against the exposures created by their CDS transactions” (Rose). Since they are not required to hold a minimum amount of capital, CDS sellers were able to create as many credit default swaps as they wanted to without limit. By 2008, credit default swaps “accounted for nearly 10% of OTC derivatives outstanding” and were worth “something close to $57 trillion in notional value” (Rose).  As put by Eric Dinallo, former Insurance Superintendent of New York, “swaps came to be used not to reduce risk, but to create or assume it” (Dinallo).  

The fall of American International Group in September 2008 highlights how the lack of regulation in credit default swaps and the OTC market directly intensified the effects of the recession. Going into the third quarter of 2008, AIG had credit fault swaps on approximately $500 billion worth of assets, $78 billion of which were on multi-sector collateralized debt obligations. Multi-sector collateralized debt obligations are complicated securities “backed by debt payments from residential and commercial mortgages, home equity loans, and more” (). As the subprime mortgage industry collapsed with the housing bubble in 2007, AIG had to start paying back many of their CDS buyers. By July 2008, AIG had to pay approximately $16.5 billion to its CDS counterparties (Rose). Because credit rating agencies were concerned about AIG’s capital, they lowered the company’s debt ratings.  In response, AIG’s CDS buyers called for $14.5 billion of collateral, sending AIG into a large and immediate liquidity crisis (Rose). AIG’s descent put the world’s financial system at risk because of the interconnected, complex nature of the financial industry, and the fact that many global firms had bought credit default swaps from AIG. If AIG had failed, many firms would have defaulted on it. Luckily, however, the United States government bailed the company out with a $180 billion loan in exchange for majority ownership. The near-fall and bailout of AIG is an undeniably prominent event in the Great Recession. 
In reflection on the recession, Born noted that “Recognizing the dangers . . . was not rocket science, but it was contrary to the conventional wisdom and certainly contrary to the economic interests of Wall Street at the moment” (Rose). Had financial regulators been more willing to listen to Born’s concerns in the 90s, the consequences of the Great Recession could have been greatly mitigated. 

##### **The Future of Over-the-Counter Derivatives and Potential Solutions**

At the Pittsburgh summit in 2009, the G20 nations met to discuss potential methods for oversight of the OTC derivative market. In the wake of the recession, leaders opted for a slow rollout of OTC requirements, agreeing that all standardized OTC derivatives get traded via central counterparty and on electronic platforms, as well as be reported to a central trade repository. The goal of these changes was to minimize counterparty risk and increase market transparency. 

The United States enacted the Dodd-Frank Wall Street Reform and Consumer Protection Act on July 21, 2010, to implement the regulations addressed at the G20 Pittsburgh summit. Title VII of the act provides a regulatory guide to the OTC market by dividing regulatory power between the SEC and CFTC. Since the act was signed, the agencies have worked together to propose many rules within the Dodd-Frank guidelines.

One solution discussed both at the G20 summit and in the Dodd-Frank Act is the implementation of central counterparties. CCPs are separate legal entities that split the initial contract of two counterparties into two so that the counterparties can adopt the CCP as their new counterparty.  Three benefits of CCP use are multilateral netting, simplified risk management, and public transparency (Cecchetti et al.). Multilateral netting refers to the summation of an individual firm’s bilateral netting and effectively reduces risk and exposure (Cecchetti et al.). While CCPs have demonstrated clear benefits within the past decade of minimizing one issue with current OTC regulations, only standardized OTC derivatives are required to utilize CCPs. Custom OTC derivatives should also be encouraged to use CCPs to minimize the most risk within the market. 

As OTC derivatives evolve in complexity and the market continues to develop innovative solutions– whether that be additional clearing houses or some other regulation–  are necessary to find a balance between growth and stability. Regulators and leaders must be open to differing opinions, recognizing that while the marketplace may appear to be thriving in its present state, long-term sustainability is not always guaranteed. 